plot(phaseobjtmp)
plot(phaseobjtmp, mode= "dec")
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 0.2))
plot(stftobjlater, mode = "pval")
plot(stftobjlatersub, mode = "pval")
tmpobj
stftobjlatersub
phaseobjx = stftphase(get.intervals(tmpobj, "08:18:32", "10:08:26")[,1],   win = 600)
phaseobjy = stftphase(get.intervals(tmpobj, "08:18:32", "10:08:26")[,2],   win = 600)
phaseobjz = stftphase(get.intervals(tmpobj, "08:18:32", "10:08:26")[,3],   win = 600)
plot(phaseobjx)
phaseobjx = stftphase(get.intervals(tmpobj, "08:18:32", "10:08:26", incl = T)[,1:2],   win = 600)
plot(phaseobjx)
phaseobjtmp = phaseobjx
phaseobjtmp$values = abs(phaseobjx$values -  phaseobjy$values)
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 0.2))
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 0.2), topthresh = 20)
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 0.5), topthresh = 20)
plot(phaseobjtmp, mode= "dec", zlim.q = c(0.5, 1), topthresh = 20)
plot(phaseobjtmp, mode= "dec", zlim.q = c(0.5, 1), topthresh = 20, median = T)
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 1), topthresh = 20, median = T)
phaseobjtmp$values = abs(phaseobjz$values -  phaseobjy$values)
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 1), topthresh = 20, median = T)
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 1), topthresh = 50, median = T)
phaseobjx$va
sort(phaseobjx$va)
plot(sort(phaseobjx$va))
phaseobjtmp$values = pmin ( abs(phaseobjz$values -  phaseobjy$values), abs(abs(phaseobjz$values -  phaseobjy$values) - 2*pi))
plot(sort(phaseobjtmp$va))
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 1), topthresh = 50, median = T)
phaseobjtmp$values = abs(phaseobjz$values -  phaseobjy$values)
for (k in  1:4) phaseobjtmp$values = pmin(phaseobjtmp$values, abs(phaseobjtmp$values - pi))
plot(phaseobjtmp, mode= "dec", zlim.q = c(0, 1), topthresh = 50, median = T)
plot(phaseobjtmp, mode= "Mod", zlim.q = c(0, 1), topthresh = 50, median = T)
plot(phaseobjtmp, mode= "mod", zlim.q = c(0, 1), topthresh = 50, median = T)
plot(phaseobjtmp, mode= "mod", zlim.q = c(0, 0.5), topthresh = 50, median = T)
plot(phaseobjtmp, mode= "mod", zlim.q = c(0, 0.5), topthresh = 20, median = T)
warnings()
plot(phaseobjtmp, mode= "mod", zlim.q = c(0, 0.5), topthresh = 20, median=T, reassign=F)
plot(phaseobjtmp, mode= "mod", zlim.q = c(0, 0.5), topthresh = 10, median=T, reassign=F)
plot(phaseobjtmp, mode= "mod", zlim.q = c(0, 0.5), topthresh = 10, median=F, reassign=F)
stftobjlatersub
phaseobjtmp
plot(phaseobjtmp, mode= "mod", zlim.q = c(0, 0.5), topthresh = 10, median=T, reassign=F)
plot(phaseobjtmp, mode= "mod", topthresh = 10, median=T, reassign=F)
plot(sort(phaseobjtmp$va))
plot(sort(phaseobjtmp$va))
plot(phaseobjtmp, mode= "mod", topthresh = 10, median=T, reassign=F)
plot(stftobjlatersub, topthresh = 10, mode = "pval", reassign = F)
plot(stftobjlatersub, topthresh = 10, mode = "pval", reassign = F, median =T)
phaseobjtmp$values = abs(phaseobjx$values -  phaseobjy$values)
for (k in  1:4) phaseobjtmp$values = pmin(phaseobjtmp$values, abs(phaseobjtmp$values - pi))
for (k in  1:4) phaseobjtmp$values = pmin(phaseobjtmp$values, abs(phaseobjtmp$values - pi))
plot(phaseobjtmp, mode= "mod", topthresh = 10, median=T, reassign=F)
phaseobjtmp$values = abs(phaseobjx$values -  phaseobjz$values)
for (k in  1:4) phaseobjtmp$values = pmin(phaseobjtmp$values, abs(phaseobjtmp$values - pi))
for (k in  1:4) phaseobjtmp$values = pmin(phaseobjtmp$values, abs(phaseobjtmp$values - pi))
plot(phaseobjtmp, mode= "mod", topthresh = 10, median=T, reassign=F)
phaseobjtmp$values = abs(phaseobjy$values -  phaseobjz$values)
for (k in  1:4) phaseobjtmp$values = pmin(phaseobjtmp$values, abs(phaseobjtmp$values - pi))
for (k in  1:4) phaseobjtmp$values = pmin(phaseobjtmp$values, abs(phaseobjtmp$values - pi))
plot(phaseobjtmp, mode= "mod", topthresh = 10, median=T, reassign=F)
dim(get.intervals(tmpobj, "08:18:32", "10:08:26"))
tmpobj2 = (get.intervals(tmpobj, "08:18:32", "10:08:26", incl = T))
bapply(1:659401, 600, function(t) cor(tmpobj2[t,1], tmpobj2[t,2]))
bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2])), cor(tmpobj2[t,2], tmpobj2[t,3])), cor(tmpobj2[t,1], tmpobj2[t,3]))))
bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))
dev.new()
plot( bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[1,])
plot( bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[1,], type="l")
plot( bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[2,], type="l")
plot( abs(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[2,]), type="l")
plot( runmed(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[2,],10), type="l")
plot( runmed(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[3,],11), type="l")
plot( runmed(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[3,],21), type="l")
plot( runmed(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[3,],21), type="l", ylab="")
plot( runmed(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[3,],21), type="l", ylab=""); abline(h=0)
plot( runmed(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[1,],21), type="l", ylab=""); abline(h=0)
plot( runmed(bapply(1:659401, 600, function(t) c(cor(tmpobj2[t,1], tmpobj2[t,2]), cor(tmpobj2[t,2], tmpobj2[t,3]), cor(tmpobj2[t,1], tmpobj2[t,3])))[2,],21), type="l", ylab=""); abline(h=0)
plot( runmed(bapply(1:659401, 600, function(t) c(cov(tmpobj2[t,1], tmpobj2[t,2]), cov(tmpobj2[t,2], tmpobj2[t,3]), cov(tmpobj2[t,1], tmpobj2[t,3])))[2,],21), type="l", ylab=""); abline(h=0)
plot( runmed(bapply(1:659401, 600, function(t) c(cov(tmpobj2[t,1], tmpobj2[t,2]), cov(tmpobj2[t,2], tmpobj2[t,3]), cov(tmpobj2[t,1], tmpobj2[t,3])))[1,],21), type="l", ylab=""); abline(h=0)
plot( runmed(bapply(1:659401, 600, function(t) c(cov(tmpobj2[t,1], tmpobj2[t,2]), cov(tmpobj2[t,2], tmpobj2[t,3]), cov(tmpobj2[t,1], tmpobj2[t,3])))[3,],21), type="l", ylab=""); abline(h=0)
plot( runmed(bapply(1:659401, 600, function(t) prcomp(tmpobj2[t,])$sd )[3,],21), type="l", ylab=""); abline(h=0)
prcomp(tmpobj2[t,])$sd
prcomp(tmpobj2[t,])
prcomp(tmpobj2[1:600,])
str(prcomp(tmpobj2[1:600,]))
plot( runmed(bapply(1:659401, 600, function(t) prcomp(tmpobj2[t,])$sd )[1,],21), type="l", ylab=""); abline(h=0)
bapply(1:659401, 600, function(t) prcomp(tmpobj2[t,])$sd ) -> probj
plot(scale(probj, center=F)[1,])
plot(scale(probj, center=F)[2,])
plot(scale(probj, center=F)[3,])
probj/ sqrt(colSums(probj^2))
probj/ rep(sqrt(colSums(probj^2)), each=3)
repeatplot(probj/ rep(sqrt(colSums(probj^2)), each=3), mar = 1, col=1:3, type="l")
source("C:/Users/zhou/PortableGit/ReadGenea/Junk/helper.R")
repeatplot(probj/ rep(sqrt(colSums(probj^2)), each=3), mar = 1, col=1:3, type="l")
repeatplot((probj/ rep(sqrt(colSums(probj^2)))^2, each=3), mar = 1, col=1:3, type="l")
repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
repeatplot((probj)^2, mar = 1, col=1:3, type="l")
repeatplot((probj)^2, mar = 1, col=1:3, type="l", log="y")
l
repeatplot((probj)^2, mar = 1, col=1:3, type="l", log="y", ylim = c(0.1, 1))
repeatplot((probj)^2, mar = 1, col=1:3, type="l", log="y", limits = F,ylim = c(0.1, 1))
repeatplot((probj)^2, mar = 1, col=1:3, type="l", log="y", lim = F,ylim = c(0.1, 1))
repeatplot((probj)^2, mar = 1, col=1:3, type="l", log="y", lim = F,ylim = c(0.05, 1))
repeatplot((probj)^2, mar = 1, col=1:3, type="l", log="y", lim = F,ylim = c(0.05, 0.5))
repeatplot((probj)^2, mar = 1, col=1:3, type="l", log="y", lim = F,ylim = c(0.01, 0.5))
repeatplot((probj)^2, mar = 1, col=1:3, type="l", lim = F,ylim = c(0.01, 0.5))
repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
repeatplot(runmed((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, 11), mar = 1, col=1:3, type="l")
probj2 = apply(probj, 1, function(t) runmed(t, 11))
repeatplot(runmed((probj2/ rep(sqrt(colSums(probj2^2)), each=3))^2, 11), mar = 1, col=1:3, type="l")
repeatplot((probj2/ rep(sqrt(colSums(probj2^2)), each=3))^2, mar = 1, col=1:3, type="l")
probj2 = t(apply(probj, 1, function(t) runmed(t, 11)))
repeatplot((probj2/ rep(sqrt(colSums(probj2^2)), each=3))^2, mar = 1, col=1:3, type="l")
dev.new()
plot(colSums(probj2^2))
repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
 bapply(1:659401, 600, function(t) prcomp(tmpobj2[t,])$sd ) -> probjrepeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
 bapply(1:659401, 600, function(t) prcomp(tmpobj2[t,])$sd ) -> probj;repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
 bapply(1:659401, 60, function(t) prcomp(tmpobj2[t,])$sd ) -> probj;repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
 bapply(1:659401, 1000, function(t) prcomp(tmpobj2[t,])$sd ) -> probj;repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
 bapply(1:659401, 100, function(t) prcomp(tmpobj2[t,])$sd ) -> probj;repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
 bapply(1:659401, 10, function(t) prcomp(tmpobj2[t,])$sd ) -> probj;repeatplot((probj/ rep(sqrt(colSums(probj^2)), each=3))^2, mar = 1, col=1:3, type="l")
history(3000)

res1 = NULL
res2 = NULL
res3 = NULL
for (k in floor(seq.log(10000, 10, 100))){
tmp= bapply(1:659401, k, function(t) prcomp(tmpobj2[t,])$sd)
res1 = rbind(res1,expand(tmp[1,], 659401))
res2 = rbind(res2,expand(tmp[2,], 659401))
res3 = rbind(res3,expand(tmp[3,], 659401))
}
